name:                massalia
version:             0.1.0.0
github:              "theobat/massalia"
license:             BSD3
author:              "theophile batoz"
maintainer:          "example@example.com"
copyright:           "2018 theophile batoz"

extra-source-files:
- README.rst
- ChangeLog.md

# Metadata use d when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/theobat/massalia#readme>

ghc-options:
  - -Wall -fno-warn-redundant-constraints -Wno-partial-type-signatures
  - -j4 +RTS -A128m -n2m -qg -RTS

dependencies:
- base >= 4.7 && < 5
- protolude
- text
- mtl
- bytestring
- vector
- uuid
- tasty
- tasty-hunit
- aeson
- inflections
- hasql
- hasql-pool
- hasql-dynamic-statements
- hasql-implicits
- range
- postgresql-binary
- email-validate
- range
- containers
- unordered-containers
- hasql-migration
- hasql-transaction
- pretty-simple
- jwt
- hasql-url
- filepattern
- filepath
- time
- morpheus-graphql >= 0.27
- morpheus-graphql-core >= 0.27
- morpheus-graphql-server >= 0.27
- scientific
- these

library:
  source-dirs: src

# executables:
#   massalia-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - massalia

tests:
  massalia-unit-test:
    main:                unit/Spec.hs
    source-dirs:
      - test
      - dataseed
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - massalia
  doctest:
    main:                Main.hs
    source-dirs:
      - doctest
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - massalia
    - doctest
  massalia-integration-test:
    main:                integration/SpecAPI.hs
    source-dirs:
      - test
      - dataseed
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - massalia
    - massalia-migration

benchmarks:
  massalia-bench:
    main: Main.hs
    source-dirs:
      - bench
      - dataseed
    ghc-options:
      - -eventlog
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N6
      - -O2
    dependencies:
      - massalia
      - criterion
